### ISSUE TITLE
XML RPC Client Example not working

### ISSUE THREAD

**Issue by farao** [byorgey/haxr#21] opened 2017-12-21 16:25 UTC
If running the example in https://hackage.haskell.org/package/haxr-3000.11.2/docs/Network-XmlRpc-Client.html only exchanging the url and the "example.add", it gives me an error of ambuous type variable:

Ambiguous type variable ‘t0’ arising from a use of ‘remote’ prevents the constraint ‘(Network.XmlRpc.Internals.XmlRpcType t0)’ from being solved.

Whole compiler error: [error.txt](https://github.com/byorgey/haxr/files/1579816/error.txt)

Strangely, when running the "remote url functionStr" in ghci, it prints me the resulting XML. But when I try to parse it, it does not work because the result is of type Remote t => t instead of String. Applying "show" manually, like in the official example, just gives me the ambiguous type error...

How can I solve this? And could you update the example to a working one for future users of the library?

**Comment by byorgey** [comment] 2017-12-24 02:18
Thanks for the report!  Which version of GHC are you using to compile?  I'll try to take a look.

**Comment by byorgey** [comment] 2018-03-07 17:48
I am not able to reproduce this.  It sounds kind of like you copied the example but didn't copy the type signature for `add`, or something like that?  The `remote` function is very polymorphic, so it definitely needs a type signature so it can pick the right instances.  I'm going to close this for now, but feel free to re-open if this doesn't solve the issue or if you have additional information.

**Closed by byorgey** 2018-03-07 17:48 UTC
